steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'builds'
  - 'submit'
  - '--config=services/time-parser/cloudbuild.yaml'
  - '.'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'builds'
  - 'submit'
  - '--config=services/dob-normalize/cloudbuild.yaml'
  - '.'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'builds'
  - 'submit'
  - '--config=services/date-formatter/cloudbuild.yaml'
  - '.'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'builds'
  - 'submit'
  - '--config=services/zipcode-validate/cloudbuild.yaml'
  - '.'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'builds'
  - 'submit'
  - '--config=services/availability/cloudbuild.yaml'
  - '.'