steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/bland-gcp-migration/bland-images/webhook-check-timeslots:$COMMIT_SHA', '-f', 'services/webhook-check-timeslots/Dockerfile', 'services/webhook-check-timeslots' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/bland-gcp-migration/bland-images/webhook-check-timeslots:$COMMIT_SHA' ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'webhook-check-timeslots'
  - '--image'
  - 'us-central1-docker.pkg.dev/bland-gcp-migration/bland-images/webhook-check-timeslots:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- 'us-central1-docker.pkg.dev/bland-gcp-migration/bland-images/webhook-check-timeslots:$COMMIT_SHA'
